name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Networking
  http: ^1.3.0

  # State management
  flutter_riverpod: ^2.5.1

  # Secure token storage
  flutter_secure_storage: ^9.0.0

  # Routing
  go_router: ^13.0.0

  # Location
  geolocator: ^10.1.0
  google_maps_flutter: ^2.6.0

  # WebSocket
  web_socket_channel: ^2.4.0

  # UI
  flutter_animate: ^4.5.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
